### PR TITLE
Fixes for Julia 1.0

### PR DESCRIPTION
**Pull request by yebai**

### CODE REVIEW

**Comment by yebai** [comment]
@hessammehr This should be working now for Julia 1.0. 

Some changes I made

- I changed the linking target for `libtask` to Julia 1.0
- I commented out some platforms which does not have Julia 1.0 binary yet.
- I fixed version of BinaryBuilder and BinaryProvider because they don't work on Julia 1.0 yet. 

Ref: 
https://github.com/TuringLang/Turing.jl/issues/466
https://github.com/TuringLang/Turing.jl/issues/462

**Comment by hessammehr** [comment]
Wonderful, thanks @yebai! I'll have a quick look in a bit but seems good to me.

**Comment by hessammehr** [comment]
I suppose we should rebase 462 on master now? Or apply these to 462 instead of master?

**Comment by yebai** [comment]
Let's apply these to 462 for now.

**Pull request merged**
